import Head from "next/head";
import { Breadcrumb, Layout, Menu, theme } from "antd";
import type { MenuProps } from "antd";
import { useState } from "react";
import Diff from "@/pages/components/Diff";

import styles from "@/styles/Home.module.css";

export default function Home() {
  const menuItems: MenuProps["items"] = [
    {
      key: "diff",
      label: "Diff",
    },
    {
      key: "json",
      label: "JSON 查看",
    },
    {
      key: "var-name",
      label: "生成变量名",
    },
  ];
  const [menuKey, setMenuKey] = useState("diff");

  return (
    <>
      <Head>
        <title>Tool 工具站</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Layout style={{ height: "100vh" }}>
          <Layout.Sider width={200} collapsible theme="light">
            <Menu
              mode="inline"
              selectedKeys={[menuKey]}
              defaultOpenKeys={[]}
              style={{ height: "100%" }}
              items={menuItems}
            />
          </Layout.Sider>
          <Layout.Content
            style={{ padding: "1rem", minHeight: 280, overflow: "auto" }}
          >
            {menuKey === "diff" ? <Diff /> : null}
          </Layout.Content>
        </Layout>
      </main>
    </>
  );
}
